theme: jekyll-theme-cayman
title: Stellar Notifications
description: Stellar Notifications is a notification system that alerts you whenever an operation has been carried out on your Stellar account.
